# Generated by Django 5.1.15 on 2026-05-09 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('completed_attempts', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('highest_score', models.FloatField(default=0)),
                ('lowest_score', models.FloatField(default=0)),
                ('pass_rate', models.FloatField(default=0)),
                ('average_time_minutes', models.FloatField(default=0)),
                ('score_distribution', models.JSONField(default=dict)),
                ('question_difficulty_stats', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessment_analytics',
            },
        ),
        migrations.CreateModel(
            name='ClassPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('average_score', models.FloatField(default=0)),
                ('participation_rate', models.FloatField(default=0)),
                ('top_topic', models.CharField(blank=True, max_length=255)),
                ('weak_topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'class_performance_snapshots',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('assessments_taken', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_activity',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('class_level', models.CharField(max_length=5)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subject_mastery',
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topic_mastery',
            },
        ),
    ]
