# Generated by Django 5.1.15 on 2026-05-09 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('assessments', '0001_initial'),
        ('classes', '0003_initial'),
        ('curriculum', '0002_initial'),
        ('students', '0002_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanalytics',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentanalytics',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classperformancesnapshot',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='classperformancesnapshot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_snapshots', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectmastery',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_masteries', to='students.student'),
        ),
        migrations.AddField(
            model_name='subjectmastery',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to='students.student'),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='curriculum.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='classperformancesnapshot',
            unique_together={('school_class', 'subject', 'week_start')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmastery',
            unique_together={('student', 'subject', 'class_level')},
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('student', 'topic')},
        ),
    ]
