# Generated by Django 5.1.15 on 2026-05-09 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'External Link'), ('text', 'Text Content')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='curriculum/resources/')),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'curriculum_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('learning_outcomes', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('advanced', 'Advanced')], default='medium', max_length=15)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'curriculum_subtopics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('class_level', models.CharField(db_index=True, max_length=5)),
                ('term', models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('week', models.PositiveIntegerField(default=1, help_text='Week in the term')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('learning_objectives', models.JSONField(default=list)),
                ('competencies', models.JSONField(default=list)),
                ('key_vocabulary', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('advanced', 'Advanced')], default='medium', max_length=15)),
                ('estimated_mastery_hours', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_generation_prompt_hint', models.TextField(blank=True, help_text='Hint for AI question generation specific to this topic')),
            ],
            options={
                'db_table': 'curriculum_topics',
                'ordering': ['class_level', 'term', 'week', 'order'],
            },
        ),
    ]
