# Generated by Django 5.1.15 on 2026-05-09 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('employee_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('can_generate_ai_content', models.BooleanField(default=True)),
                ('can_override_ai_marks', models.BooleanField(default=True)),
                ('can_publish_results', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='classes.schoolclass')),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['user__last_name'],
            },
        ),
    ]
