# Generated by Django 5.1.15 on 2026-05-09 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0002_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDailyTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('theme', models.CharField(max_length=255)),
                ('daily_goal', models.TextField()),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holiday_daily_tasks',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='HolidayActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('revision', 'Revision'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('reading', 'Reading')], max_length=20)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
                ('daily_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='holidays.holidaydailytask')),
            ],
            options={
                'db_table': 'holiday_activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HolidayPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('class_level', models.CharField(max_length=5)),
                ('holiday_type', models.CharField(choices=[('term1_end', 'End of Term 1'), ('term2_end', 'End of Term 2'), ('term3_end', 'End of Term 3')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holiday_packages',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='holidaydailytask',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='holidays.holidaypackage'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaydailytask',
            unique_together={('package', 'day_number')},
        ),
        migrations.CreateModel(
            name='StudentHolidayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_completed', models.PositiveIntegerField(default=0)),
                ('activities_completed', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('completion_percentage', models.FloatField(default=0)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('holiday_streak', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.holidaypackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'student_holiday_progress',
                'unique_together': {('student', 'package')},
            },
        ),
    ]
