# Generated by Django 5.1.15 on 2026-05-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('students', '0002_initial'),
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('overall', 'Overall School'), ('class', 'Class'), ('subject', 'Subject'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('holiday', 'Holiday')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'db_table': 'leaderboards',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('assessments_completed', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboards.leaderboard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
                'unique_together': {('leaderboard', 'student')},
            },
        ),
    ]
