# Generated by Django 5.1.15 on 2026-05-09 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('students', '0002_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text_answer', models.TextField(blank=True)),
                ('matching_answer', models.JSONField(default=dict)),
                ('drag_drop_answer', models.JSONField(default=list)),
                ('arrangement_answer', models.JSONField(default=list)),
                ('selected_labels', models.JSONField(default=list, help_text='For diagram labeling')),
                ('ai_score', models.FloatField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(default=0)),
                ('teacher_score', models.FloatField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('final_score', models.FloatField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('hint_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('daily_revision', 'Daily Revision'), ('weekly_quiz', 'Weekly Quiz'), ('topic_test', 'Topic Test'), ('term_exam', 'Terminal Exam'), ('mock_exam', 'Mock Exam'), ('holiday_revision', 'Holiday Revision'), ('adaptive_test', 'Adaptive Test'), ('diagnostic', 'Diagnostic Test'), ('ple_practice', 'PLE Practice')], db_index=True, max_length=30)),
                ('class_level', models.CharField(db_index=True, max_length=5)),
                ('term', models.PositiveIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], default=1)),
                ('academic_year', models.PositiveIntegerField()),
                ('total_marks', models.FloatField(default=0)),
                ('passing_marks', models.FloatField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=40)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('active', 'Active / Live'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('anti_cheat_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='classes.schoolclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='subjects.subject')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('ai_marked', 'AI Marked'), ('teacher_reviewed', 'Teacher Reviewed'), ('published', 'Published')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('ai_score', models.FloatField(default=0)),
                ('teacher_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('teacher_comment', models.TextField(blank=True)),
                ('ai_overall_feedback', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for suspicious activity')),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='students.student')),
            ],
            options={
                'db_table': 'assessment_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks_override', models.FloatField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.assessment')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['order'],
            },
        ),
    ]
