# Generated by Django 5.1.15 on 2026-05-09 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('language', 'Language'), ('stem', 'STEM'), ('social', 'Social Studies'), ('religious', 'Religious Education'), ('practical', 'Practical')], default='core', max_length=20)),
                ('class_levels', models.JSONField(default=list, help_text='List of class levels e.g. ["P1","P2","P3"]')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Hex color for UI', max_length=20)),
                ('is_examinable', models.BooleanField(default=True, help_text='Appears in PLE/exams')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['order', 'name'],
            },
        ),
    ]
