# Generated by Django 5.1.15 on 2026-05-09 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'parent_guardians',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('stream', models.CharField(blank=True, max_length=10)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('special_needs', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['current_class', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_mastery', models.FloatField(default=0.0)),
                ('learning_speed', models.CharField(choices=[('slow', 'Slow'), ('average', 'Average'), ('fast', 'Fast')], default='average', max_length=20)),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('strong_subjects', models.JSONField(default=list)),
                ('weak_subjects', models.JSONField(default=list)),
                ('strong_topics', models.JSONField(default=list)),
                ('weak_topics', models.JSONField(default=list)),
                ('learning_style', models.CharField(blank=True, max_length=50)),
                ('ai_notes', models.TextField(blank=True)),
                ('total_questions_attempted', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('ple_readiness_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_ai_profiles',
            },
        ),
    ]
