# Generated by Django 5.1.15 on 2026-05-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLEReadinessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('english_score', models.FloatField(default=0)),
                ('mathematics_score', models.FloatField(default=0)),
                ('science_score', models.FloatField(default=0)),
                ('sst_score', models.FloatField(default=0)),
                ('predicted_aggregate', models.CharField(blank=True, max_length=10)),
                ('confidence_level', models.FloatField(default=0)),
                ('ai_analysis', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ple_readiness', to='students.student')),
            ],
            options={
                'db_table': 'ple_readiness_scores',
            },
        ),
    ]
