# Generated by Django 5.1.15 on 2026-05-09 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('matching', 'Matching'), ('composition', 'Composition / Essay'), ('comprehension', 'Comprehension'), ('spelling', 'Spelling'), ('drag_drop', 'Drag and Drop'), ('image_based', 'Image-Based'), ('audio_based', 'Audio-Based'), ('sentence_arrangement', 'Sentence Arrangement'), ('diagram_labeling', 'Diagram Labeling')], db_index=True, max_length=30)),
                ('class_level', models.CharField(db_index=True, max_length=5)),
                ('term', models.PositiveIntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], null=True)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('question_audio', models.FileField(blank=True, null=True, upload_to='questions/audio/')),
                ('question_html', models.TextField(blank=True, help_text='Rich HTML version for web rendering')),
                ('marks', models.FloatField(default=1.0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('estimated_time_seconds', models.PositiveIntegerField(default=60)),
                ('source', models.CharField(choices=[('ai_generated', 'AI Generated'), ('teacher_created', 'Teacher Created'), ('imported', 'Imported'), ('past_paper', 'Past Paper')], db_index=True, default='ai_generated', max_length=20)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('ai_prompt_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('correct_rate', models.FloatField(default=0.0, help_text='Percentage of correct answers historically')),
                ('tags', models.JSONField(default=list)),
                ('learning_objectives', models.JSONField(default=list)),
                ('adaptive_tags', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.topic')),
            ],
            options={
                'db_table': 'question_bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=5)),
                ('option_text', models.TextField()),
                ('option_image', models.ImageField(blank=True, null=True, upload_to='questions/options/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question')),
            ],
            options={
                'db_table': 'mcq_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=255)),
                ('right_text', models.CharField(max_length=255)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='questions/matching/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='questions/matching/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='question_bank.question')),
            ],
            options={
                'db_table': 'matching_pairs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FillBlankSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_text', models.TextField()),
                ('is_blank', models.BooleanField(default=False)),
                ('blank_answer', models.CharField(blank=True, max_length=255)),
                ('accepted_answers', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='question_bank.question')),
            ],
            options={
                'db_table': 'fill_blank_segments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_keywords', models.JSONField(default=list, help_text='Keywords for AI marking')),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation')),
                ('hints', models.JSONField(default=list)),
                ('marking_guide', models.TextField(blank=True)),
                ('marking_rubric', models.JSONField(default=dict, help_text='Rubric for composition/essay marking')),
                ('minimum_keywords_required', models.PositiveIntegerField(default=1)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question_bank.question')),
            ],
            options={
                'db_table': 'question_answers',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'class_level', 'difficulty'], name='question_ba_subject_b160a0_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'is_approved', 'is_active'], name='question_ba_questio_c9464a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'class_level'], name='question_ba_topic_i_98b888_idx'),
        ),
    ]
